require "rubygems"
require "erb"

role = ENV["role"]
boot_package_url = "file:///home/vagrant/configuration-master/build/boot.tar.gz"
#boot_script = ERB.new(File.read("scripts/boot.erb")).result(binding)
boot_script = ""
Vagrant::Config.run do |configuration|
  configuration.vm.box = "centos57_86_64"
  configuration.vm.box_url = "http://dl.dropbox.com/u/8072848/centos-5.7-x86_64.box"
  configuration.vm.customize [
    "modifyvm", :id,
    "--name", "configuration-master",
    "--memory", "1024"
  ]
  configuration.vm.host_name = "configuration-master"
  configuration.vm.forward_port 8153, 8153
  configuration.vm.share_folder "..", "/home/vagrant/configuration-master", ".."
  configuration.vm.provision :shell, :inline => boot_script
end
